import { StyleSheet } from 'react-native';
import { ms } from 'react-native-size-matters';

import { fonts, fs, lightColors, type AppColors } from '@/theme';

const SCREEN_PADDING = ms(16);
const HEADER_BUTTON = ms(40);
const HOST_AVATAR = ms(44);
const PERSON_AVATAR = ms(36);
const ONLINE_DOT = ms(13);

export type ActivityDetailStyles = ReturnType<typeof createStyles>;

export function createStyles(colors: AppColors) {
  const softShadow = {
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowRadius: ms(4),
    shadowOffset: { width: 0, height: ms(1) },
    elevation: 1,
  };

  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    flex: {
      flex: 1,
    },
    flexShrink: {
      flexShrink: 1,
    },
    pressed: {
      opacity: 0.85,
      transform: [{ scale: 0.97 }],
    },
    mutedText: {
      fontSize: fs(11.5),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },

    header: {
      height: ms(56),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SCREEN_PADDING,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerCenter: {
      position: 'absolute',
      left: SCREEN_PADDING + HEADER_BUTTON * 2,
      right: SCREEN_PADDING + HEADER_BUTTON * 2,
      alignItems: 'center',
    },
    headerBrand: {
      fontSize: fs(10),
      fontFamily: fonts.semibold,
      letterSpacing: 1.6,
      textTransform: 'uppercase',
      color: colors.textSecondary,
    },
    headerTitle: {
      fontSize: fs(15.5),
      fontFamily: fonts.bold,
      letterSpacing: -0.3,
      color: colors.text,
    },
    headerActions: {
      flexDirection: 'row',
      gap: ms(6),
    },
    headerButton: {
      width: HEADER_BUTTON,
      height: HEADER_BUTTON,
      borderRadius: HEADER_BUTTON / 2,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.surfaceMuted,
      backgroundColor: colors.card,
      ...softShadow,
    },

    scroll: {
      padding: SCREEN_PADDING,
      paddingBottom: ms(24),
      gap: ms(16),
    },

    hero: {
      height: ms(208),
      borderRadius: ms(18),
      overflow: 'hidden',
      backgroundColor: colors.surfaceHigh,
    },
    heroMap: {
      ...StyleSheet.absoluteFill,
    },
    heroShade: {
      ...StyleSheet.absoluteFill,
      backgroundImage: `linear-gradient(to top, ${colors.black}D9 0%, ${colors.black}59 55%, ${colors.black}1A 100%)`,
    },
    heroTop: {
      position: 'absolute',
      top: ms(12),
      left: ms(12),
      right: ms(12),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ms(8),
    },
    liveBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(6),
      paddingHorizontal: ms(10),
      paddingVertical: ms(5),
      borderRadius: ms(999),
      borderWidth: 1,
      borderColor: `${colors.white}26`,
      backgroundColor: `${colors.black}73`,
    },
    liveBadgeText: {
      fontSize: fs(11.5),
      fontFamily: fonts.semibold,
      color: colors.white,
    },
    tagBadge: {
      paddingHorizontal: ms(10),
      paddingVertical: ms(5),
      borderRadius: ms(999),
      backgroundColor: `${colors.white}E6`,
    },
    tagBadgeText: {
      fontSize: fs(11.5),
      fontFamily: fonts.bold,
      color: lightColors.text,
    },
    heroBottom: {
      position: 'absolute',
      left: ms(12),
      right: ms(12),
      bottom: ms(12),
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: ms(10),
    },
    routeLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(4),
    },
    routeLabel: {
      fontSize: fs(11.5),
      fontFamily: fonts.medium,
      color: `${colors.white}CC`,
    },
    routeName: {
      fontSize: fs(16.5),
      lineHeight: fs(21),
      fontFamily: fonts.bold,
      letterSpacing: -0.3,
      color: colors.white,
    },
    viewMap: {
      width: ms(32),
      height: ms(32),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: ms(10),
      borderWidth: 1,
      borderColor: `${colors.white}33`,
      backgroundColor: `${colors.white}33`,
    },
    heroTapArea: {
      ...StyleSheet.absoluteFill,
    },
    heroActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(6),
    },
    directions: {
      height: ms(32),
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(5),
      paddingHorizontal: ms(12),
      borderRadius: ms(10),
      borderWidth: 1,
      borderColor: `${colors.white}33`,
      backgroundColor: `${colors.white}33`,
    },
    directionsText: {
      fontSize: fs(11.5),
      fontFamily: fonts.semibold,
      color: colors.white,
    },
    pin: {
      alignItems: 'center',
    },
    pinHead: {
      width: ms(34),
      height: ms(34),
      borderRadius: ms(17),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.white,
      backgroundColor: colors.primary,
      shadowColor: colors.black,
      shadowOpacity: 0.25,
      shadowRadius: ms(4),
      shadowOffset: { width: 0, height: ms(2) },
      elevation: 4,
    },
    pinEmoji: {
      width: fs(18),
      height: fs(18),
      fontSize: fs(14),
      lineHeight: fs(18),
      textAlign: 'center',
      includeFontPadding: false,
    },
    pinTail: {
      width: 0,
      height: 0,
      marginTop: -ms(1),
      borderLeftWidth: ms(6),
      borderRightWidth: ms(6),
      borderTopWidth: ms(8),
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderTopColor: colors.white,
    },
    checkInButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(4),
      paddingHorizontal: ms(12),
      paddingVertical: ms(8),
      borderRadius: ms(999),
      backgroundColor: colors.success,
      shadowColor: colors.success,
      shadowOpacity: 0.3,
      shadowRadius: ms(6),
      shadowOffset: { width: 0, height: ms(3) },
      elevation: 3,
    },
    checkInButtonDisabled: {
      backgroundColor: colors.textSecondary,
      shadowOpacity: 0,
      elevation: 0,
      opacity: 0.5,
    },
    checkInText: {
      fontSize: fs(12.5),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    checkInHint: {
      marginTop: ms(4),
      fontSize: fs(11.5),
      lineHeight: fs(15),
      fontFamily: fonts.medium,
      color: colors.textSecondary,
    },

    joinedBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(12),
      padding: ms(14),
      borderRadius: ms(16),
      borderWidth: 1,
      borderColor: `${colors.success}33`,
      backgroundColor: `${colors.success}14`,
    },
    joinedBannerIcon: {
      width: ms(30),
      height: ms(30),
      borderRadius: ms(15),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.success,
    },
    joinedBannerTitle: {
      fontSize: fs(14),
      fontFamily: fonts.bold,
      color: colors.success,
    },
    joinedBannerText: {
      marginTop: ms(2),
      fontSize: fs(12),
      lineHeight: fs(17),
      fontFamily: fonts.medium,
      color: colors.textSecondary,
    },
    card: {
      padding: ms(16),
      gap: ms(14),
      borderRadius: ms(18),
      backgroundColor: colors.card,
      ...softShadow,
    },
    titleBlock: {
      gap: ms(6),
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(8),
    },
    instantBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(3),
      paddingHorizontal: ms(8),
      paddingVertical: ms(3),
      borderRadius: ms(999),
      backgroundColor: `${colors.primarySoft}99`,
    },
    instantText: {
      fontSize: fs(10),
      fontFamily: fonts.bold,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: colors.primary,
    },
    title: {
      fontSize: fs(19),
      lineHeight: fs(25),
      fontFamily: fonts.bold,
      letterSpacing: -0.4,
      color: colors.text,
    },

    hostStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ms(10),
      padding: ms(12),
      borderRadius: ms(14),
      backgroundColor: colors.surface,
    },
    hostInfo: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(12),
    },
    hostAvatar: {
      width: HOST_AVATAR,
      height: HOST_AVATAR,
      borderRadius: HOST_AVATAR / 2,
      borderWidth: 2,
      borderColor: colors.card,
    },
    onlineDot: {
      position: 'absolute',
      right: -1,
      bottom: -1,
      width: ONLINE_DOT,
      height: ONLINE_DOT,
      borderRadius: ONLINE_DOT / 2,
      borderWidth: 2,
      borderColor: colors.card,
      backgroundColor: colors.success,
    },
    awayDot: {
      backgroundColor: colors.textMuted,
    },
    hostNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      columnGap: ms(6),
      rowGap: ms(2),
    },
    hostName: {
      flexShrink: 1,
      fontSize: fs(13.5),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    subline: {
      marginTop: ms(4),
    },
    trustBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(2),
      paddingHorizontal: ms(6),
      paddingVertical: ms(2),
      borderRadius: ms(6),
      backgroundColor: colors.success,
    },
    trustText: {
      fontSize: fs(9.5),
      fontFamily: fonts.bold,
      color: colors.card,
    },
    messageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(4),
      height: ms(34),
      paddingHorizontal: ms(12),
      borderRadius: ms(10),
      backgroundColor: colors.surfaceHigh,
    },
    messageText: {
      fontSize: fs(12),
      fontFamily: fonts.semibold,
      color: colors.text,
    },

    tiles: {
      flexDirection: 'row',
      gap: ms(8),
    },
    tile: {
      flex: 1,
      padding: ms(10),
      borderRadius: ms(12),
      backgroundColor: colors.surface,
    },
    tileLabelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(4),
      marginBottom: ms(4),
    },
    tileLabel: {
      flexShrink: 1,
      fontSize: fs(10.5),
      fontFamily: fonts.semibold,
    },
    tileValue: {
      fontSize: fs(12.5),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    tileHint: {
      marginTop: ms(2),
      fontSize: fs(10.5),
      fontFamily: fonts.regular,
      color: colors.textSecondary,
    },
    description: {
      paddingTop: ms(12),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      fontSize: fs(13),
      lineHeight: fs(20),
      fontFamily: fonts.regular,
      color: colors.textWarm,
    },

    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: ms(8),
    },
    sectionTitleRow: {
      flexShrink: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(8),
    },
    sectionTitle: {
      fontSize: fs(14.5),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    sectionTitleLarge: {
      fontSize: fs(15.5),
      fontFamily: fonts.bold,
      color: colors.text,
    },
    countPill: {
      paddingHorizontal: ms(8),
      paddingVertical: ms(2),
      borderRadius: ms(999),
      backgroundColor: `${colors.primarySoft}99`,
    },
    countPillText: {
      fontSize: fs(10.5),
      fontFamily: fonts.bold,
      color: colors.primary,
    },
    spotsText: {
      fontSize: fs(11.5),
      fontFamily: fonts.semibold,
      color: colors.primaryDark,
    },
    mutedPill: {
      paddingHorizontal: ms(8),
      paddingVertical: ms(2),
      borderRadius: ms(999),
      backgroundColor: colors.surfaceHigh,
    },
    mutedPillText: {
      fontSize: fs(10.5),
      fontFamily: fonts.medium,
      color: colors.textSecondary,
    },
    seeMore: {
      fontSize: fs(12),
      fontFamily: fonts.medium,
      color: colors.primary,
    },

    progressTrack: {
      height: ms(8),
      marginTop: -ms(4),
      borderRadius: ms(4),
      overflow: 'hidden',
      backgroundColor: colors.surfaceMuted,
    },
    progressFill: {
      height: '100%',
      borderRadius: ms(4),
      backgroundColor: colors.primary,
    },
    personRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(12),
      paddingVertical: ms(9),
    },
    personDivider: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    personAvatar: {
      width: PERSON_AVATAR,
      height: PERSON_AVATAR,
      borderRadius: PERSON_AVATAR / 2,
    },
    personBody: {
      flex: 1,
    },
    personNameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(6),
    },
    personName: {
      flexShrink: 1,
      fontSize: fs(13),
      fontFamily: fonts.semibold,
      color: colors.text,
    },
    hostBadge: {
      paddingHorizontal: ms(5),
      paddingVertical: ms(1),
      borderRadius: ms(4),
      backgroundColor: colors.primarySoft,
    },
    hostBadgeText: {
      fontSize: fs(9.5),
      fontFamily: fonts.bold,
      color: colors.primary,
    },
    meAvatar: {
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: `${colors.success}4D`,
      backgroundColor: `${colors.success}1A`,
    },
    meAvatarText: {
      fontSize: fs(12),
      fontFamily: fonts.bold,
      color: colors.success,
    },
    meBadge: {
      paddingHorizontal: ms(5),
      paddingVertical: ms(1),
      borderRadius: ms(4),
      backgroundColor: `${colors.success}1F`,
    },
    meBadgeText: {
      fontSize: fs(9.5),
      fontFamily: fonts.bold,
      color: colors.success,
    },
    readyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(3),
    },
    readyText: {
      fontSize: fs(11),
      fontFamily: fonts.medium,
      color: colors.success,
    },
    nearbyCard: {
      padding: ms(14),
      gap: ms(10),
      borderRadius: ms(18),
      backgroundColor: colors.card,
      ...softShadow,
    },
    nearbyTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: ms(8),
    },
    nearbyStats: {
      alignItems: 'flex-end',
    },
    trustValue: {
      fontSize: fs(11),
      fontFamily: fonts.bold,
      color: colors.success,
    },
    freeBadge: {
      paddingHorizontal: ms(6),
      paddingVertical: ms(1),
      borderRadius: ms(4),
      backgroundColor: colors.success,
    },
    soonBadge: {
      backgroundColor: colors.surfaceHigh,
    },
    freeText: {
      fontSize: fs(9.5),
      fontFamily: fonts.bold,
      color: colors.card,
    },
    soonText: {
      color: colors.textWarm,
    },
    interests: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: ms(6),
    },
    interest: {
      paddingHorizontal: ms(8),
      paddingVertical: ms(3),
      borderRadius: ms(6),
      backgroundColor: colors.surface,
    },
    interestText: {
      fontSize: fs(11),
      fontFamily: fonts.medium,
      color: colors.textWarm,
    },
    nearbyActions: {
      flexDirection: 'row',
      gap: ms(8),
      paddingTop: ms(10),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    nearbyButton: {
      flex: 1,
      height: ms(34),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ms(4),
      borderRadius: ms(10),
      backgroundColor: colors.surfaceHigh,
    },
    nearbyButtonText: {
      fontSize: fs(12),
      fontFamily: fonts.medium,
      color: colors.text,
    },
    nearbyButtonTextMuted: {
      color: colors.textSecondary,
    },
    inviteButton: {
      backgroundColor: `${colors.primarySoft}B3`,
    },
    inviteText: {
      fontFamily: fonts.semibold,
      color: colors.primaryDark,
    },
    invitedButton: {
      backgroundColor: colors.mint,
    },
    invitedText: {
      fontFamily: fonts.semibold,
      color: colors.success,
    },

    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(10),
      paddingHorizontal: SCREEN_PADDING,
      paddingTop: ms(12),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
      shadowColor: colors.black,
      shadowOpacity: 0.06,
      shadowRadius: ms(12),
      shadowOffset: { width: 0, height: -ms(4) },
      elevation: 8,
    },
    statusNote: {
      flex: 1,
      minHeight: ms(50),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ms(8),
      paddingHorizontal: ms(16),
      borderRadius: ms(14),
      backgroundColor: colors.surfaceMuted,
    },
    statusNoteText: {
      flexShrink: 1,
      fontSize: fs(13.5),
      lineHeight: fs(18),
      fontFamily: fonts.semibold,
      color: colors.textSecondary,
    },
    leaveButton: {
      height: ms(50),
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(6),
      paddingHorizontal: ms(16),
      borderRadius: ms(14),
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    leaveText: {
      fontSize: fs(14),
      fontFamily: fonts.semibold,
      color: colors.danger,
    },
    joinButton: {
      flex: 1,
      height: ms(50),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: ms(10),
      paddingHorizontal: ms(16),
      borderRadius: ms(14),
      backgroundColor: colors.primary,
      shadowColor: colors.primary,
      shadowOpacity: 0.35,
      shadowRadius: ms(10),
      shadowOffset: { width: 0, height: ms(6) },
      elevation: 4,
    },
    joinButtonDone: {
      backgroundColor: colors.success,
      shadowColor: colors.success,
    },
    chatBadge: {
      position: 'absolute',
      top: -ms(7),
      right: -ms(5),
      minWidth: ms(22),
      height: ms(22),
      paddingHorizontal: ms(6),
      borderRadius: ms(11),
      borderWidth: ms(2),
      borderColor: colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    chatBadgeMuted: {
      backgroundColor: colors.textMuted,
    },
    chatBadgeText: {
      fontSize: fs(11),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    joinButtonDisabled: {
      opacity: 0.5,
    },
    joinLabel: {
      flexShrink: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: ms(8),
    },
    joinText: {
      flexShrink: 1,
      fontSize: fs(14),
      fontFamily: fonts.bold,
      color: colors.white,
    },
    joinPill: {
      paddingHorizontal: ms(8),
      paddingVertical: ms(3),
      borderRadius: ms(999),
      backgroundColor: `${colors.black}33`,
    },
    joinPillText: {
      fontSize: fs(10.5),
      fontFamily: fonts.semibold,
      color: colors.white,
    },

    memberMarker: {
      width: ms(34),
      height: ms(34),
      borderRadius: ms(17),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2.5,
      borderColor: colors.white,
      backgroundColor: colors.surfaceHigh,
      shadowColor: colors.black,
      shadowOpacity: 0.25,
      shadowRadius: ms(4),
      shadowOffset: { width: 0, height: ms(2) },
      elevation: 4,
    },
    memberMarkerArrived: {
      borderColor: colors.success,
    },
    memberMarkerMe: {
      borderColor: colors.white,
      backgroundColor: colors.primary,
    },
    memberMarkerAvatar: {
      width: '100%',
      height: '100%',
      borderRadius: ms(17),
    },
    memberMarkerInitials: {
      fontSize: fs(11),
      fontFamily: fonts.bold,
      color: colors.white,
    },
  });
}
