/**
 * Bundles the Twemoji SVGs used by the sticker packs into
 * src/assets/twemoji/index.ts so stickers render offline.
 *
 * Run after editing the emoji in src/services/stickers.ts:
 *   yarn twemoji
 */
const fs = require('fs');
const path = require('path');

const VERSION = '15.1.0';
const BASE = `https://cdn.jsdelivr.net/gh/jdecked/twemoji@${VERSION}/assets/svg`;
const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'src/services/stickers.ts');
const OUTPUT = path.join(ROOT, 'src/assets/twemoji/index.ts');

/** Must match twemojiCode() in src/components/Twemoji.tsx. */
function twemojiCode(emoji) {
  const text = emoji.includes('\u200d') ? emoji : emoji.replace(/\uFE0F/g, '');
  return Array.from(text)
    .map(char => char.codePointAt(0).toString(16))
    .join('-');
}

async function main() {
  const source = fs.readFileSync(SOURCE, 'utf8');
  const emojis = [
    ...new Set(
      [...source.matchAll(/'([^']+)'/g)]
        .map(match => match[1])
        .filter(text => /^[^ -~]+$/.test(text)),
    ),
  ];
  const codes = [...new Set(emojis.map(twemojiCode))].sort();

  const entries = await Promise.all(
    codes.map(async code => {
      const response = await fetch(`${BASE}/${code}.svg`);
      if (!response.ok) {
        throw new Error(`${code}: HTTP ${response.status}`);
      }
      return [code, (await response.text()).trim()];
    }),
  );

  const body = entries
    .map(([code, svg]) => `  '${code}': ${JSON.stringify(svg)},`)
    .join('\n');
  const output = `// Generated by scripts/build-twemoji.js — do not edit by hand.
//
// Twemoji ${VERSION} (https://github.com/jdecked/twemoji)
// Copyright 2019 Twitter, Inc and other contributors.
// Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

export const TWEMOJI_SVG: Record<string, string> = {
${body}
};
`;
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, output);
  console.log(`Bundled ${entries.length} Twemoji SVGs into ${OUTPUT}`);
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
